### ISSUE TITLE
CDS-298 cads-mars-server result to CePH

### ISSUE THREAD

**Issue by EddyCMWF** [ecmwf-projects/cads-adaptors#218]
Write cads-mars-server results directly to CePH

**Comment by malmans2** [comment]
Quick comment about this: When you zip/convert to netcdf, I think it might be better to only write the final file directly on ceph.

**Comment by EddyCMWF** [comment]
Hi Mattia,
I think this relates massively to the intermediate caching we are discussing in other channels, and may also require a slight refactor of how we call MARS. Maybe via the DirectMarsAdaptor
Eddy
